# 数据科学 100 道练习 11~20

In [1]:
import polars as pl
from helper.polars import load_100knocks_data
pl.Config.set_fmt_str_lengths(100)
df_customer, df_category, df_product, df_receipt, df_store, df_geocode = load_100knocks_data()

## P-011

从顾客数据（df_customer）中，只抽取顾客 ID（customer_id）末位为 1 的记录的全部字段，显示 10 条。

In [2]:
(
df_customer
.filter(pl.col.customer_id.str.ends_with('1'))
.head(5)
)

shape: (5, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ customer_n ┆ gender_cd ┆ gender ┆ … ┆ address   ┆ applicati ┆ applicati ┆ status_cd │
│ d          ┆ ame        ┆ ---       ┆ ---    ┆   ┆ ---       ┆ on_store_ ┆ on_date   ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ str       ┆ cd        ┆ ---       ┆ str       │
│ str        ┆ str        ┆           ┆        ┆   ┆           ┆ ---       ┆ i64       ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CS03761300 ┆ 六角 雅彦  ┆ 9         ┆ 不明   ┆ … ┆ 東京都江  ┆ S13037    ┆ 20150414  ┆ 0-0000000 │
│ 0071       ┆            ┆           ┆        ┆   ┆ 東区南砂* ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS02881100 ┆ 堀井       ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14028    ┆ 20160115  ┆ 0-0000000 │
│ 0001       ┆ かおり     ┆           ┆        ┆   ┆ 横浜市泉  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 区和泉町* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS04041200 ┆ 川井 郁恵  ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14040    ┆ 20151101  ┆ 1-2009102 │
│ 0191       ┆            ┆           ┆        ┆   ┆ 横浜市緑  ┆           ┆           ┆ 5-4       │
│            ┆            ┆           ┆        ┆   ┆ 区北八朔  ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ 町******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS02831400 ┆ 小菅       ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14028    ┆ 20151123  ┆ 1-2008042 │
│ 0011       ┆ あおい     ┆           ┆        ┆   ┆ 横浜市瀬  ┆           ┆           ┆ 6-5       │
│            ┆            ┆           ┆        ┆   ┆ 谷区宮沢* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS03921200 ┆ 藤島       ┆ 1         ┆ 女性   ┆ … ┆ 東京都杉  ┆ S13039    ┆ 20171121  ┆ 1-2010021 │
│ 0051       ┆ 恵梨香     ┆           ┆        ┆   ┆ 並区阿佐  ┆           ┆           ┆ 5-4       │
│            ┆            ┆           ┆        ┆   ┆ 谷北***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

## P-012

从店铺数据（df_store）中，只显示地址（address）包含 "横浜市" 的记录的全部字段。

In [3]:
(
df_store
.filter(pl.col.address.str.contains("横浜市"))
)

shape: (11, 10)
┌──────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ store_cd ┆ store_name ┆ prefectur ┆ prefectur ┆ … ┆ tel_no    ┆ longitude ┆ latitude ┆ floor_are │
│ ---      ┆ ---        ┆ e_cd      ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---      ┆ a         │
│ str      ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64      ┆ ---       │
│          ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆          ┆ f64       │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ S14010   ┆ 菊名店     ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.6326  ┆ 35.50049 ┆ 1732.0    │
│          ┆            ┆           ┆           ┆   ┆ 032       ┆           ┆          ┆           │
│ S14033   ┆ 阿久和店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.4961  ┆ 35.45918 ┆ 1495.0    │
│          ┆            ┆           ┆           ┆   ┆ 043       ┆           ┆          ┆           │
│ S14040   ┆ 長津田店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.4994  ┆ 35.52398 ┆ 1548.0    │
│          ┆            ┆           ┆           ┆   ┆ 046       ┆           ┆          ┆           │
│ S14050   ┆ 阿久和西店 ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.4961  ┆ 35.45918 ┆ 1830.0    │
│          ┆            ┆           ┆           ┆   ┆ 053       ┆           ┆          ┆           │
│ S14028   ┆ 二ツ橋店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.4963  ┆ 35.46304 ┆ 1574.0    │
│          ┆            ┆           ┆           ┆   ┆ 042       ┆           ┆          ┆           │
│ …        ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ S14046   ┆ 北山田店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.5916  ┆ 35.56189 ┆ 831.0     │
│          ┆            ┆           ┆           ┆   ┆ 049       ┆           ┆          ┆           │
│ S14011   ┆ 日吉本町店 ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.6316  ┆ 35.54655 ┆ 890.0     │
│          ┆            ┆           ┆           ┆   ┆ 033       ┆           ┆          ┆           │
│ S14048   ┆ 中川中央店 ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.5758  ┆ 35.54912 ┆ 1657.0    │
│          ┆            ┆           ┆           ┆   ┆ 051       ┆           ┆          ┆           │
│ S14042   ┆ 新山下店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.6593  ┆ 35.43894 ┆ 1044.0    │
│          ┆            ┆           ┆           ┆   ┆ 047       ┆           ┆          ┆           │
│ S14006   ┆ 葛が谷店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.5633  ┆ 35.53573 ┆ 1886.0    │
│          ┆            ┆           ┆           ┆   ┆ 031       ┆           ┆          ┆           │
└──────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

## P-013

从顾客数据（df_customer）中，抽取状态码（status_cd）以字母 A〜F 开头的数据的全部字段，显示 10 条。

In [4]:
(
df_customer
.filter(pl.col.status_cd.str.contains('^[A-F]'))
.head(5)
)

shape: (5, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ customer_n ┆ gender_cd ┆ gender ┆ … ┆ address   ┆ applicati ┆ applicati ┆ status_cd │
│ d          ┆ ame        ┆ ---       ┆ ---    ┆   ┆ ---       ┆ on_store_ ┆ on_date   ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ str       ┆ cd        ┆ ---       ┆ str       │
│ str        ┆ str        ┆           ┆        ┆   ┆           ┆ ---       ┆ i64       ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CS03141500 ┆ 宇多田     ┆ 1         ┆ 女性   ┆ … ┆ 東京都渋  ┆ S13031    ┆ 20150529  ┆ D-2010032 │
│ 0172       ┆ 貴美子     ┆           ┆        ┆   ┆ 谷区代々  ┆           ┆           ┆ 5-C       │
│            ┆            ┆           ┆        ┆   ┆ 木******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS01541400 ┆ 奥野 陽子  ┆ 1         ┆ 女性   ┆ … ┆ 東京都江  ┆ S13015    ┆ 20150722  ┆ B-2010060 │
│ 0103       ┆            ┆           ┆        ┆   ┆ 東区北砂* ┆           ┆           ┆ 9-B       │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS01121500 ┆ 芦田 沙耶  ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14011    ┆ 20150228  ┆ C-2010042 │
│ 0048       ┆            ┆           ┆        ┆   ┆ 横浜市港  ┆           ┆           ┆ 1-9       │
│            ┆            ┆           ┆        ┆   ┆ 北区日吉  ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ 本町***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
│ CS02941500 ┆ 梅田 里穂  ┆ 1         ┆ 女性   ┆ … ┆ 千葉県浦  ┆ S12029    ┆ 20150610  ┆ D-2010091 │
│ 0023       ┆            ┆           ┆        ┆   ┆ 安市富士  ┆           ┆           ┆ 8-E       │
│            ┆            ┆           ┆        ┆   ┆ 見******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS03541500 ┆ 寺沢 真希  ┆ 9         ┆ 不明   ┆ … ┆ 東京都世  ┆ S13035    ┆ 20141220  ┆ F-2010102 │
│ 0029       ┆            ┆           ┆        ┆   ┆ 田谷区玉  ┆           ┆           ┆ 9-F       │
│            ┆            ┆           ┆        ┆   ┆ 川台***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

## P-014

从顾客数据（df_customer）中，抽取状态码（status_cd）末位为数字 1〜9 的数据的全部字段，显示 10 条。

In [5]:
(
df_customer
.filter(pl.col.status_cd.str.contains('[1-9]$'))
.head(5)
)

shape: (5, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ customer_n ┆ gender_cd ┆ gender ┆ … ┆ address   ┆ applicati ┆ applicati ┆ status_cd │
│ d          ┆ ame        ┆ ---       ┆ ---    ┆   ┆ ---       ┆ on_store_ ┆ on_date   ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ str       ┆ cd        ┆ ---       ┆ str       │
│ str        ┆ str        ┆           ┆        ┆   ┆           ┆ ---       ┆ i64       ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CS00121500 ┆ 田崎 美紀  ┆ 1         ┆ 女性   ┆ … ┆ 東京都大  ┆ S13001    ┆ 20170605  ┆ 6-2009092 │
│ 0145       ┆            ┆           ┆        ┆   ┆ 田区仲六  ┆           ┆           ┆ 9-2       │
│            ┆            ┆           ┆        ┆   ┆ 郷******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS03351300 ┆ 安斎 遥    ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14033    ┆ 20150728  ┆ 6-2008050 │
│ 0180       ┆            ┆           ┆        ┆   ┆ 横浜市旭  ┆           ┆           ┆ 6-5       │
│            ┆            ┆           ┆        ┆   ┆ 区善部町* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS01121500 ┆ 芦田 沙耶  ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14011    ┆ 20150228  ┆ C-2010042 │
│ 0048       ┆            ┆           ┆        ┆   ┆ 横浜市港  ┆           ┆           ┆ 1-9       │
│            ┆            ┆           ┆        ┆   ┆ 北区日吉  ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ 本町***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
│ CS04041200 ┆ 川井 郁恵  ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14040    ┆ 20151101  ┆ 1-2009102 │
│ 0191       ┆            ┆           ┆        ┆   ┆ 横浜市緑  ┆           ┆           ┆ 5-4       │
│            ┆            ┆           ┆        ┆   ┆ 区北八朔  ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ 町******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS00931500 ┆ 皆川 文世  ┆ 1         ┆ 女性   ┆ … ┆ 東京都世  ┆ S13009    ┆ 20150319  ┆ 5-2008032 │
│ 0023       ┆            ┆           ┆        ┆   ┆ 田谷区駒  ┆           ┆           ┆ 2-1       │
│            ┆            ┆           ┆        ┆   ┆ 沢******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

## P-015

从顾客数据（df_customer）中，抽取状态码（status_cd）以字母 A〜F 开头、且末位为数字 1〜9 的数据的全部字段，显示 10 条。

In [6]:
(
df_customer
.filter(pl.col.status_cd.str.contains('^[A-F].*[1-9]$'))
.head(5)
)

shape: (5, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ customer_n ┆ gender_cd ┆ gender ┆ … ┆ address   ┆ applicati ┆ applicati ┆ status_cd │
│ d          ┆ ame        ┆ ---       ┆ ---    ┆   ┆ ---       ┆ on_store_ ┆ on_date   ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ str       ┆ cd        ┆ ---       ┆ str       │
│ str        ┆ str        ┆           ┆        ┆   ┆           ┆ ---       ┆ i64       ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CS01121500 ┆ 芦田 沙耶  ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14011    ┆ 20150228  ┆ C-2010042 │
│ 0048       ┆            ┆           ┆        ┆   ┆ 横浜市港  ┆           ┆           ┆ 1-9       │
│            ┆            ┆           ┆        ┆   ┆ 北区日吉  ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ 本町***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
│ CS02251300 ┆ 島村       ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14022    ┆ 20150320  ┆ A-2009111 │
│ 0105       ┆ 貴美子     ┆           ┆        ┆   ┆ 逗子市山  ┆           ┆           ┆ 5-7       │
│            ┆            ┆           ┆        ┆   ┆ の根***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
│ CS00151500 ┆ 水野 陽子  ┆ 9         ┆ 不明   ┆ … ┆ 東京都大  ┆ S13001    ┆ 20150614  ┆ A-2010072 │
│ 0096       ┆            ┆           ┆        ┆   ┆ 田区蒲田  ┆           ┆           ┆ 4-7       │
│            ┆            ┆           ┆        ┆   ┆ 本町***** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *****     ┆           ┆           ┆           │
│ CS01361500 ┆ 西脇 季衣  ┆ 1         ┆ 女性   ┆ … ┆ 千葉県千  ┆ S12013    ┆ 20150128  ┆ B-2010032 │
│ 0053       ┆            ┆           ┆        ┆   ┆ 葉市美浜  ┆           ┆           ┆ 9-6       │
│            ┆            ┆           ┆        ┆   ┆ 区幕張西* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS02041200 ┆ 小宮 薫    ┆ 1         ┆ 女性   ┆ … ┆ 東京都板  ┆ S13020    ┆ 20150822  ┆ B-2008102 │
│ 0161       ┆            ┆           ┆        ┆   ┆ 橋区東坂  ┆           ┆           ┆ 1-3       │
│            ┆            ┆           ┆        ┆   ┆ 下******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

## P-016

从店铺数据（df_store）中，显示电话号码（tel_no）为 3 位-3 位-4 位格式的记录的全部字段。

In [7]:
(
df_store
.filter(pl.col.tel_no.str.contains(r'^\d{3}-\d{3}-\d{4}$'))
)

shape: (34, 10)
┌──────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ store_cd ┆ store_name ┆ prefectur ┆ prefectur ┆ … ┆ tel_no    ┆ longitude ┆ latitude ┆ floor_are │
│ ---      ┆ ---        ┆ e_cd      ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---      ┆ a         │
│ str      ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64      ┆ ---       │
│          ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆          ┆ f64       │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ S12014   ┆ 千草台店   ┆ 12        ┆ 千葉県    ┆ … ┆ 043-123-4 ┆ 140.118   ┆ 35.63559 ┆ 1698.0    │
│          ┆            ┆           ┆           ┆   ┆ 003       ┆           ┆          ┆           │
│ S13002   ┆ 国分寺店   ┆ 13        ┆ 東京都    ┆ … ┆ 042-123-4 ┆ 139.4802  ┆ 35.70566 ┆ 1735.0    │
│          ┆            ┆           ┆           ┆   ┆ 008       ┆           ┆          ┆           │
│ S14010   ┆ 菊名店     ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.6326  ┆ 35.50049 ┆ 1732.0    │
│          ┆            ┆           ┆           ┆   ┆ 032       ┆           ┆          ┆           │
│ S14033   ┆ 阿久和店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.4961  ┆ 35.45918 ┆ 1495.0    │
│          ┆            ┆           ┆           ┆   ┆ 043       ┆           ┆          ┆           │
│ S14036   ┆ 相模原中央 ┆ 14        ┆ 神奈川県  ┆ … ┆ 042-123-4 ┆ 139.3716  ┆ 35.57327 ┆ 1679.0    │
│          ┆ 店         ┆           ┆           ┆   ┆ 045       ┆           ┆          ┆           │
│ …        ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ S14045   ┆ 厚木店     ┆ 14        ┆ 神奈川県  ┆ … ┆ 046-123-4 ┆ 139.3651  ┆ 35.44182 ┆ 980.0     │
│          ┆            ┆           ┆           ┆   ┆ 048       ┆           ┆          ┆           │
│ S12029   ┆ 東野店     ┆ 12        ┆ 千葉県    ┆ … ┆ 047-123-4 ┆ 139.8968  ┆ 35.65086 ┆ 1101.0    │
│          ┆            ┆           ┆           ┆   ┆ 004       ┆           ┆          ┆           │
│ S12053   ┆ 高洲店     ┆ 12        ┆ 千葉県    ┆ … ┆ 047-123-4 ┆ 139.9176  ┆ 35.63755 ┆ 1555.0    │
│          ┆            ┆           ┆           ┆   ┆ 006       ┆           ┆          ┆           │
│ S14024   ┆ 三田店     ┆ 14        ┆ 神奈川県  ┆ … ┆ 044-123-4 ┆ 139.5424  ┆ 35.6077  ┆ 972.0     │
│          ┆            ┆           ┆           ┆   ┆ 038       ┆           ┆          ┆           │
│ S14006   ┆ 葛が谷店   ┆ 14        ┆ 神奈川県  ┆ … ┆ 045-123-4 ┆ 139.5633  ┆ 35.53573 ┆ 1886.0    │
│          ┆            ┆           ┆           ┆   ┆ 031       ┆           ┆          ┆           │
└──────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

## P-017

把顾客数据（df_customer）按出生日期（birth_day）排序，年长者在前，从开头显示全部字段的 10 条。

In [8]:
(
df_customer
.sort(
    by='birth_day', 
    descending=False
)
.head()
)

shape: (5, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ customer_n ┆ gender_cd ┆ gender ┆ … ┆ address   ┆ applicati ┆ applicati ┆ status_cd │
│ d          ┆ ame        ┆ ---       ┆ ---    ┆   ┆ ---       ┆ on_store_ ┆ on_date   ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ str       ┆ cd        ┆ ---       ┆ str       │
│ str        ┆ str        ┆           ┆        ┆   ┆           ┆ ---       ┆ i64       ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CS00381300 ┆ 村山       ┆ 1         ┆ 女性   ┆ … ┆ 東京都調  ┆ S13003    ┆ 20160214  ┆ 0-0000000 │
│ 0014       ┆ 菜々美     ┆           ┆        ┆   ┆ 布市菊野  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 台******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS02681300 ┆ 吉村 朝陽  ┆ 1         ┆ 女性   ┆ … ┆ 神奈川県  ┆ S14026    ┆ 20150723  ┆ 0-0000000 │
│ 0004       ┆            ┆           ┆        ┆   ┆ 藤沢市辻  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 堂元町*** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *******   ┆           ┆           ┆           │
│ CS01881100 ┆ 熊沢 美里  ┆ 1         ┆ 女性   ┆ … ┆ 東京都清  ┆ S13018    ┆ 20150403  ┆ 0-0000000 │
│ 0003       ┆            ┆           ┆        ┆   ┆ 瀬市野塩* ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS02780300 ┆ 内村 拓郎  ┆ 0         ┆ 男性   ┆ … ┆ 神奈川県  ┆ S14027    ┆ 20151227  ┆ 0-0000000 │
│ 0004       ┆            ┆           ┆        ┆   ┆ 藤沢市鵠  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 沼藤が谷* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS01380100 ┆ 天野 拓郎  ┆ 0         ┆ 男性   ┆ … ┆ 千葉県船  ┆ S12013    ┆ 20160120  ┆ 0-0000000 │
│ 0003       ┆            ┆           ┆        ┆   ┆ 橋市前原  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 東******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
(
df_customer
.select(
    pl.col('customer_name', 'birth_day', 'age')
        .sort_by('birth_day')
)
.head()
)

shape: (5, 3)
┌───────────────┬────────────┬─────┐
│ customer_name ┆ birth_day  ┆ age │
│ ---           ┆ ---        ┆ --- │
│ str           ┆ str        ┆ i64 │
╞═══════════════╪════════════╪═════╡
│ 村山 菜々美   ┆ 1928-11-26 ┆ 90  │
│ 吉村 朝陽     ┆ 1928-12-14 ┆ 90  │
│ 熊沢 美里     ┆ 1929-01-07 ┆ 90  │
│ 内村 拓郎     ┆ 1929-01-12 ┆ 90  │
│ 天野 拓郎     ┆ 1929-01-15 ┆ 90  │
└───────────────┴────────────┴─────┘

## P-018

把顾客数据（df_customer）按出生日期（birth_day）排序，年轻者在前，从开头显示全部字段的 10 条。

In [10]:
(
df_customer
.sort(
    by='birth_day', 
    descending=True
)
.head()
)

shape: (5, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ customer_n ┆ gender_cd ┆ gender ┆ … ┆ address   ┆ applicati ┆ applicati ┆ status_cd │
│ d          ┆ ame        ┆ ---       ┆ ---    ┆   ┆ ---       ┆ on_store_ ┆ on_date   ┆ ---       │
│ ---        ┆ ---        ┆ str       ┆ str    ┆   ┆ str       ┆ cd        ┆ ---       ┆ str       │
│ str        ┆ str        ┆           ┆        ┆   ┆           ┆ ---       ┆ i64       ┆           │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CS03511400 ┆ 大村 美里  ┆ 1         ┆ 女性   ┆ … ┆ 東京都世  ┆ S13035    ┆ 20150619  ┆ 6-2009120 │
│ 0004       ┆            ┆           ┆        ┆   ┆ 田谷区桜* ┆           ┆           ┆ 5-6       │
│            ┆            ┆           ┆        ┆   ┆ ********* ┆           ┆           ┆           │
│ CS02210300 ┆ 福山       ┆ 9         ┆ 不明   ┆ … ┆ 神奈川県  ┆ S14022    ┆ 20160909  ┆ 0-0000000 │
│ 0002       ┆ はじめ     ┆           ┆        ┆   ┆ 逗子市逗  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 子******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS00211300 ┆ 柴田       ┆ 1         ┆ 女性   ┆ … ┆ 東京都小  ┆ S13002    ┆ 20160304  ┆ 0-0000000 │
│ 0009       ┆ 真悠子     ┆           ┆        ┆   ┆ 金井市貫  ┆           ┆           ┆ 0-0       │
│            ┆            ┆           ┆        ┆   ┆ 井南町*** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *******   ┆           ┆           ┆           │
│ CS00411500 ┆ 松井 京子  ┆ 1         ┆ 女性   ┆ … ┆ 東京都中  ┆ S13004    ┆ 20161120  ┆ 1-2008123 │
│ 0014       ┆            ┆           ┆        ┆   ┆ 野区上鷺  ┆           ┆           ┆ 1-1       │
│            ┆            ┆           ┆        ┆   ┆ 宮******* ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ ***       ┆           ┆           ┆           │
│ CS00211400 ┆ 山内 遥    ┆ 1         ┆ 女性   ┆ … ┆ 東京都小  ┆ S13002    ┆ 20160920  ┆ 6-2010051 │
│ 0010       ┆            ┆           ┆        ┆   ┆ 金井市貫  ┆           ┆           ┆ 0-1       │
│            ┆            ┆           ┆        ┆   ┆ 井北町*** ┆           ┆           ┆           │
│            ┆            ┆           ┆        ┆   ┆ *******   ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

## P-019

对收据明细数据（df_receipt），按每条记录的销售金额（amount）从高到低添加排名，从开头显示 10 条。显示项目为顾客 ID（customer_id）、销售金额（amount）和添加的排名。销售金额（amount）相同时赋予相同名次。

In [11]:
(
df_receipt
.select(
    pl.col('customer_id', 'amount')
        .sort_by('amount', descending=True)
)
.with_columns(
    pl.col.amount
        .rank(method='min', descending=True)
        .alias('rank')
)
.head(10)
)

shape: (10, 3)
┌────────────────┬────────┬──────┐
│ customer_id    ┆ amount ┆ rank │
│ ---            ┆ ---    ┆ ---  │
│ str            ┆ i64    ┆ u32  │
╞════════════════╪════════╪══════╡
│ CS011415000006 ┆ 10925  ┆ 1    │
│ ZZ000000000000 ┆ 6800   ┆ 2    │
│ CS028605000002 ┆ 5780   ┆ 3    │
│ CS015515000034 ┆ 5480   ┆ 4    │
│ ZZ000000000000 ┆ 5480   ┆ 4    │
│ ZZ000000000000 ┆ 5480   ┆ 4    │
│ ZZ000000000000 ┆ 5440   ┆ 7    │
│ CS021515000089 ┆ 5440   ┆ 7    │
│ CS015515000083 ┆ 5280   ┆ 9    │
│ CS017414000114 ┆ 5280   ┆ 9    │
└────────────────┴────────┴──────┘

## P-020

对收据明细数据（df_receipt），按每条记录的销售金额（amount）从高到低添加排名，从开头显示 10 条。显示项目为顾客 ID（customer_id）、销售金额（amount）和添加的排名。销售金额（amount）相同时也要赋予不同名次。

In [12]:
(
df_receipt
.select(
    pl.col('customer_id', 'amount')
        .sort_by('amount', descending=True)
)
.with_columns(
    pl.col.amount
        .rank(method='ordinal', descending=True)
        .alias('rank')
)
.head(10)
)

shape: (10, 3)
┌────────────────┬────────┬──────┐
│ customer_id    ┆ amount ┆ rank │
│ ---            ┆ ---    ┆ ---  │
│ str            ┆ i64    ┆ u32  │
╞════════════════╪════════╪══════╡
│ CS011415000006 ┆ 10925  ┆ 1    │
│ ZZ000000000000 ┆ 6800   ┆ 2    │
│ CS028605000002 ┆ 5780   ┆ 3    │
│ CS015515000034 ┆ 5480   ┆ 4    │
│ ZZ000000000000 ┆ 5480   ┆ 5    │
│ ZZ000000000000 ┆ 5480   ┆ 6    │
│ ZZ000000000000 ┆ 5440   ┆ 7    │
│ CS021515000089 ┆ 5440   ┆ 8    │
│ CS015515000083 ┆ 5280   ┆ 9    │
│ CS017414000114 ┆ 5280   ┆ 10   │
└────────────────┴────────┴──────┘